### ISSUE TITLE
add sha256sum of image as a label

### ISSUE THREAD

**Issue by jbpratt** [ContainerCraft/kmi#17]
This will allow us to short circuit the CircleCI workflow by immediately checking if the image needs to be rebuilt and bailing out (halting) if not.

`Look up sha256sum of flavor in index.json, compare to label on remote image, halt if matching.`

**Comment by usrbinkat** [comment]
IIRC this is an un-recoverable chicken/egg scenario.

We cannot know the image sha until the image is fully built, once we know the image sha, if we add that as a label to the image, the image sha will change as a result.

**Comment by jbpratt** [comment]
Sorry @usrbinkat I didn't make this clear enough. I want to short circuit based on the sha256sum of the qcow2 disk image. I spent some time thinking about this morning and I have yet to figure out a way to stick a unique label on the image(s) (in the case arm64 and amd64 will have different sums).

**Comment by usrbinkat** [comment]
Ah, we can create a ${QCOW2_FILE}.sha256 file [here](https://github.com/ContainerCraft/kmi/blob/c4a70cb8057d6df9c4fb41ea01b6bdf40982a66e/hack/customize.sh#L83) and then add the shasum file path to `persist_to_workspace` [here](https://github.com/ContainerCraft/kmi/blob/c4a70cb8057d6df9c4fb41ea01b6bdf40982a66e/.circleci/config.yml#L383).

From there we can read in the sum and create a label for each child qcow2 arch image.

**Comment by jbpratt** [comment]
closing this issue, I'm taking a different approach to halt the jobs.
