### ISSUE TITLE
ci: bumping KubeVirt to v0.49.0 fails to schedule VM

### ISSUE THREAD

**Issue by jbpratt** [ContainerCraft/kmi#29]
Bumping CI KubeVirt version in https://github.com/jbpratt/kmi/commit/ceb2a958115534ad67c4b2425b1f4f149e82e918 results in failure to schedule the VM. Archived logs can be found in the action run.

```
default              42s         Warning   FailedScheduling          pod/virt-launcher-testvm-cnrsq                                        0/2 nodes are available: 1 Insufficient devices.kubevirt.io/kvm, 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```

https://github.com/ContainerCraft/kmi/actions/runs/1643716526

**Comment by usrbinkat** [comment]
Need to add this to cluster startup to remove the taint, could also add a toleration to the vm yaml instead but I would rather not as that could result in unwanted scheduling on masters in the future depending on the ci route we continue with later.
```sh
kubectl taint nodes --all --overwrite node-role.kubernetes.io/master-
```

**Comment by jbpratt** [comment]
v0.49.0 has been released, let's move on to that.
